package com.koreatravel.tabitomo.controller;

import com.koreatravel.tabitomo.domain.dto.storybook.StorybookListDTO;
import com.koreatravel.tabitomo.domain.dto.trip.CitiesDTO;
import com.koreatravel.tabitomo.domain.dto.member.MemberProfileDTO;
import com.koreatravel.tabitomo.service.trip.CitiesService;
import com.koreatravel.tabitomo.service.storybook.EditorService;

import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;

import org.springframework.core.io.Resource;
import org.springframework.core.io.ResourceLoader;
import org.springframework.http.CacheControl;
import org.springframework.http.HttpHeaders;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.userdetails.UserDetails;
import org.springframework.security.web.csrf.CsrfToken;
import org.springframework.web.bind.annotation.*;

import com.koreatravel.tabitomo.service.member.MemberService;
import com.koreatravel.tabitomo.domain.entity.member.MemberEntity;
import org.springframework.web.bind.annotation.ResponseBody;

import jakarta.servlet.http.HttpSession;
import jakarta.servlet.http.HttpServletRequest;

import org.springframework.ui.Model;
import org.springframework.stereotype.Controller;

import java.util.List;
import java.util.Map;
import java.util.HashMap;
import java.util.UUID;

@Slf4j
@Controller
@RequiredArgsConstructor
public class WebController {
    // Required args constructor is generated by Lombok's @RequiredArgsConstructor

    private final ResourceLoader resourceLoader;
    private final CitiesService citiesService;
    private final EditorService editorService;
    private final MemberService memberService;

    @GetMapping("/")
    public String index(Model model, HttpSession session, Authentication authentication, HttpServletRequest request) {
        log.info("===== Accessing root path =====");
        log.info("Session ID: {}", session.getId());
        
        // Check authentication using Spring Security
        boolean isAuthenticated = authentication != null && authentication.isAuthenticated() && 
                               !(authentication.getPrincipal() instanceof String && authentication.getPrincipal().equals("anonymousUser"));
        
        // Add authentication status to model
        model.addAttribute("isAuthenticated", isAuthenticated);
        model.addAttribute("sessionId", session.getId());
        
        // Initialize default values
        String nickname = "";
        String email = "";
        boolean questionnaireCompleted = false;
        boolean showQuestionnairePrompt = false;
        UUID memberUuid = null;
        
        // Add cities and story list to the model
        List<CitiesDTO> cities = citiesService.getRecommendCities();
        model.addAttribute("cities", cities);
        
        List<StorybookListDTO> storybookList = editorService.getmainStory();
        model.addAttribute("storylist", storybookList);
        
        // Handle authenticated user
        if (isAuthenticated && authentication.getPrincipal() instanceof UserDetails) {
            UserDetails userDetails = (UserDetails) authentication.getPrincipal();
            String username = userDetails.getUsername();
            log.info("Loading profile for user (email): {}", username);
            try {
                // Always get the latest member info from database
                MemberEntity memberEntity = memberService.findMemberByEmail(username);
                if (memberEntity != null) {
                    // Set user information
                    email = memberEntity.getEmail() != null ? memberEntity.getEmail() : "";
                    nickname = memberEntity.getNickname() != null ? memberEntity.getNickname() : "";
                    questionnaireCompleted = memberEntity.isQuestionnaireCompleted();
                    memberUuid = memberEntity.getId();
                    
                    log.info("Member UUID: {}", memberUuid);
                    
                    log.info("Loaded member info - nickname: {}, email: {}, questionnaireCompleted: {}", 
                        nickname, email, questionnaireCompleted);
                    
                    // Update session with fresh data
                    MemberProfileDTO memberProfile = MemberProfileDTO.builder()
                        .id(memberUuid)  // Add member ID
                        .email(email)
                        .nickname(nickname)
                        .profileImageUrl(memberEntity.getProfileImageUrl())
                        .questionnaireCompleted(questionnaireCompleted)
                        .build();
                    
                    session.setAttribute("memberProfile", memberProfile);
                    
                    // Handle questionnaire prompt
                    log.info("=== QUESTIONNAIRE PROMPT DEBUG ===");
                    log.info("BEFORE - questionnaireCompleted: {}, showQuestionnairePrompt: {}", questionnaireCompleted, showQuestionnairePrompt);
                    
                    if (questionnaireCompleted) {
                        // If questionnaire is completed, make sure prompt is not shown
                        session.removeAttribute("showQuestionnairePrompt");
                        showQuestionnairePrompt = false;
                        log.info("Questionnaire already completed for user: {}", nickname);
                    } else {
                        // Always show the prompt for users who haven't completed the questionnaire
                        showQuestionnairePrompt = true;
                        session.setAttribute("showQuestionnairePrompt", true);
                        log.info("Showing questionnaire prompt for user: {}", nickname);
                    }
                    
                    // Log final state
                    log.info("AFTER - questionnaireCompleted: {}, showQuestionnairePrompt: {}", questionnaireCompleted, showQuestionnairePrompt);
                    log.info("Session showQuestionnairePrompt: {}", session.getAttribute("showQuestionnairePrompt"));
                } else {
                    log.warn("Member not found in database: {}", username);
                }
            } catch (Exception e) {
                log.error("Error loading member profile: {}", e.getMessage(), e);
            }
        } else {
            // For non-authenticated users, make sure no prompt is shown
            model.addAttribute("showQuestionnairePrompt", false);
            model.addAttribute("questionnaireCompleted", false);
            log.debug("User is not authenticated, questionnaire prompt will not be shown");
        }
        
        // Always show questionnaire prompt for authenticated users who haven't completed it
        if (isAuthenticated && !questionnaireCompleted) {
            showQuestionnairePrompt = true;
            session.setAttribute("showQuestionnairePrompt", true);
        }
        
        // Add user info to model
        model.addAttribute("username", nickname);
        model.addAttribute("email", email);
        model.addAttribute("uuid", memberUuid != null ? memberUuid.toString() : "");
        model.addAttribute("questionnaireCompleted", questionnaireCompleted);
        model.addAttribute("showQuestionnairePrompt", showQuestionnairePrompt);
        
        // Add CSRF token to model if available
        CsrfToken csrfToken = (CsrfToken) request.getAttribute("_csrf");
        if (csrfToken != null) {
            model.addAttribute("_csrf", csrfToken);
            log.debug("CSRF Token: {}", csrfToken.getToken());
            
            // Log session attributes for debugging
            if (log.isDebugEnabled()) {
                log.debug("Session attributes:");
                session.getAttributeNames().asIterator()
                    .forEachRemaining(name -> 
                        log.debug("  {} = {}", name, session.getAttribute(name))
                    );
            }
        }
        
        log.debug("Successfully prepared index page");
        return "index";
    }

    @GetMapping("/menu")
    public String menu() {
        log.debug("Accessing menu page");
        return "menu";
    }

    @GetMapping("/chat")
    public String chat() {
        log.debug("Accessing chat page");
        return "chat";
    }
    
    @GetMapping("/api/session-data")
    @ResponseBody
    public Map<String, Object> getSessionData(HttpSession session) {
        Map<String, Object> sessionData = new HashMap<>();
        sessionData.put("sessionId", session.getId());
        sessionData.put("showQuestionnairePrompt", session.getAttribute("showQuestionnairePrompt"));
        sessionData.put("memberProfile", session.getAttribute("memberProfile"));
        
        // Log all session attributes for debugging
        if (log.isDebugEnabled()) {
            log.debug("Current session attributes:");
            session.getAttributeNames().asIterator()
                .forEachRemaining(name -> 
                    log.debug("  {} = {}", name, session.getAttribute(name))
                );
        }
        
        return sessionData;
    }
    
    @GetMapping(value = "/image/logo.png", produces = MediaType.IMAGE_PNG_VALUE)
    @ResponseBody
    public ResponseEntity<Resource> getLogo() {
        Resource resource = resourceLoader.getResource("classpath:static/image/logo.png");
        return ResponseEntity.ok()
                .cacheControl(CacheControl.noCache().mustRevalidate())
                .header(HttpHeaders.CONTENT_DISPOSITION, "inline; filename=logo.png")
                .body(resource);
    }

    @GetMapping("/error")
    public String showErrorPage(
            @RequestParam(value = "message", required = false) String message,
            @RequestParam(value = "code", required = false) String errorCode,
            Model model) {
        
        model.addAttribute("message", message != null ? message : "알 수 없는 오류가 발생했습니다.");
        model.addAttribute("code", errorCode);
        return "error";
    }
}
