spring.application.name=tabitomo
server.port=8085

# DB mySQL
spring.datasource.url=jdbc:mysql://localhost:3306/tabitomo?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=0000
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Gemini 여행 추천 ai
google.gemini.api-key=AIzaSyAe5uoOCDifwo4UIvQzxOS7Nk_aSsvHus4

# Kakao 지오코딩,주소변환
kakao.local.api.key=6187a77ecd882c3a50833f2cc4d189b0
kakao.api.key=${kakao.local.api.key}
kakao.js.key=3938fb7e40c57b5a83795d8b75572b8

# OpenWeatherMap 날씨
openweathermap.api.key=9e09534ec29fece026f337cfcfb5338e

# Pixabay 그림
pixabay.api.key=51766772-91e06a7339d33710d975b9b86

# Google Maps 구글맵
google.maps.api.key=AIzaSyBIblK-ON_7KwtJOAtjFy2j3Rxc7fbAmqg

# Google Cloud Translation
# Google Cloud TRANSLATE API URL = 'https://translation.googleapis.com/language/translate/v2'
google.cloud.translation.api-key=AIzaSyDre1rauiEvC0y3hcNBQlgnL2xTxDwB3fE

# Available languages: ko (Korean), en (English), ja (Japanese)
app.supported-languages=ko,en,ja

# Thymeleaf
spring.thymeleaf.cache=false

# Exclude Spring Cloud Function AutoConfiguration
spring.autoconfigure.exclude=org.springframework.cloud.function.context.config.ContextFunctionCatalogAutoConfiguration

debug=true
